- filesmap:
    rule:
      source_delete: false
      source_storage_days: -1
    source_dir:
      dir: /dev4/
      drive: test
    source_host:
      host: 192.168.31.32
      namelocalpc: astra
      pcname: NOUT-PC
      pwd: veronica
      username: NOUT
    target:
    - rule:
        source_delete: true
        source_storage_days: 61
      target_dir:
        dir: "/NOUT/\u041C\u043E\u0438 \u0434\u043E\u043A\u0443\u043C\u0435\u043D\u0442\
          \u044B/test/"
        drive: Users
      target_host:
        host: 192.168.31.32
        namelocalpc: astra
        pcname: NOUT-PC
        pwd: veronica
        username: NOUT
  method: 1
  name: test
